// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrksjqavebztyvzjhjus.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indya3NqcWF2ZWJ6dHl2empoanVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwODc1ODksImV4cCI6MjA3MzY2MzU4OX0.wDdcAT_N35YpQ_U8_NDZMDkwIN1Y05_QyhTj_JiZwWU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});